sudo: required

env:
  - VERSION=0.7.0

services:
  - docker

before_install:
  - docker version
  - docker network create --driver=bridge --subnet=192.168.0.0/16 --opt="com.docker.network.driver.mtu=1450" --opt="com.docker.network.bridge.name=redd0" nanobox
  - sudo apt-get -y install python-pip
  - sudo pip install docker==2.7.0 docker-squash
  - docker build -t nanobox/faktory:$VERSION ./$VERSION

script:
  - sudo stdbuf -oL test/run_all.sh $VERSION
  - sudo stdbuf -oL hooks/test/run_all.sh ${VERSION}

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - "echo \"Branch: '$BRANCH'; Version: '$VERSION'\";"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t ${NAMESPACE}/faktory ./${VERSION};
  - docker-squash -t ${NAMESPACE}/faktory:squashed --tmp-dir /var/tmp/squasher ${NAMESPACE}/faktory
  
  # `$VERSION-beta` tag is always pushed (master or any dev branch)
  - docker tag ${NAMESPACE}/faktory:squashed ${NAMESPACE}/faktory:${VERSION}-beta;
  - docker push ${REMOTE}${NAMESPACE}/faktory:${VERSION}-beta;
  
  # `beta` tag is always pushed (master or any dev branch)
  - if [ "$VERSION" == "0.7.0" ]; then
      docker tag ${NAMESPACE}/faktory:squashed ${NAMESPACE}/faktory:beta;
      docker push ${REMOTE}${NAMESPACE}/faktory:beta;
    fi
    
  # `latest` tag is only pushed on master && most recent version
  - if [ "$BRANCH" == "master" ] && [ "$VERSION" == "0.7.0" ]; then
      docker tag ${NAMESPACE}/faktory:squashed ${NAMESPACE}/faktory;
      docker push ${REMOTE}${NAMESPACE}/faktory;
    fi
    
  # `$VERSION` (latest/stable implied) tag is only pushed on master. tag branch for clarity otherwise (`$VERSION-$BRANCH`)
  - if [ "$BRANCH" == "master" ]; then
      docker tag ${NAMESPACE}/faktory:squashed ${NAMESPACE}/faktory:${VERSION};
      docker push ${REMOTE}${NAMESPACE}/faktory:${VERSION};
    else
      docker tag ${NAMESPACE}/faktory:squashed ${NAMESPACE}/faktory:${VERSION}-${BRANCH//\//_};
      docker push ${REMOTE}${NAMESPACE}/faktory:${VERSION}-${BRANCH//\//_};
    fi
